import FarzullaProofs.Basic
import FarzullaProofs.QuantumOscillatory.Interference
import FarzullaProofs.AxiomOfConsent.Friction
import FarzullaProofs.ROM.Basic
import FarzullaProofs.IdentityThesis.Basic
import FarzullaProofs.IdentityThesis.SetTheory
import FarzullaProofs.IdentityThesis.Structuralism
