#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
COVERAGE = ROOT / "coverage.json"
CLAIMS = ROOT / "claims_matrix.json"
PAPERMAP_ROOT = ROOT / "FarzullaProofs"
DEFAULT_REPORT = ROOT / "reports" / "paper_verification_report.md"

HEAD_RE = re.compile(r"^##\s+(.*)$")
BULLET_RE = re.compile(r"^-\s+(.*)$")


def parse_sections(text: str) -> Dict[str, List[str]]:
    sections: Dict[str, List[str]] = {}
    cur = None
    for line in text.splitlines():
        m = HEAD_RE.match(line.strip())
        if m:
            cur = m.group(1).strip()
            sections[cur] = []
            continue
        if cur is not None:
            sections[cur].append(line.rstrip("\n"))
    return sections


def bullets(lines: List[str]) -> List[str]:
    out = []
    for line in lines:
        m = BULLET_RE.match(line.strip())
        if m:
            out.append(m.group(1).strip())
    return out


def papermap_status(module: str) -> str:
    pm = PAPERMAP_ROOT / module / "PaperMap.md"
    if not pm.exists():
        return ""
    sections = parse_sections(pm.read_text(encoding="utf-8"))
    for heading, lines in sections.items():
        if heading.strip().lower() == "status":
            bs = bullets(lines)
            return bs[0] if bs else ""
    return ""


def severity(flag: bool) -> str:
    return "FAIL" if flag else "PASS"


def main() -> int:
    ap = argparse.ArgumentParser(description="Verify claims/status consistency and emit report.")
    ap.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    args = ap.parse_args()

    cov = json.loads(COVERAGE.read_text(encoding="utf-8"))
    cm = json.loads(CLAIMS.read_text(encoding="utf-8"))

    cov_by_module = {p["module"]: p["status"] for p in cov["papers"]}
    cm_papers = {p["module"]: p for p in cm["papers"]}

    modules = sorted(set(cov_by_module) | set(cm_papers))
    rows = []
    fail = False

    for module in modules:
        cov_status = cov_by_module.get(module, "")
        cm_status = cm_papers.get(module, {}).get("status", "")
        pm_status = papermap_status(module)

        status_mismatch = not (cov_status == cm_status == pm_status and cov_status != "")

        claims = [c for c in cm["claims"] if c["module"] == module]
        claim_count = len(claims)
        transfer_claims = [c for c in claims if "transfer" in c["mapping_section"].lower()]
        transfer_without_tags = [c for c in transfer_claims if not c.get("assumption_tags")]
        gold_claims = [c for c in claims if "gold" in c["mapping_section"].lower()]
        gold_or_transfer = [c for c in claims if ("gold" in c["mapping_section"].lower() or
                                                  "transfer" in c["mapping_section"].lower())]
        missing_claim_level = [
            c for c in gold_or_transfer if c.get("assumption_scope") != "claim_level"
        ]

        # Rule: gold/silver modules must have non-empty paper-level assumption tags.
        paper_tags = cm_papers.get(module, {}).get("assumption_tags", [])
        gold_needs_tags = "gold" in cov_status
        silver_needs_tags = "silver" in cov_status
        gold_missing_tags = gold_needs_tags and not paper_tags
        silver_missing_tags = silver_needs_tags and not paper_tags

        # Rule: modules with transfer claims should have assumption tags in matrix.
        transfer_missing_tags = len(transfer_without_tags) > 0
        # Rule: for gold modules, all gold/transfer claims should be claim-level tagged.
        gold_claim_level_missing = gold_needs_tags and len(missing_claim_level) > 0

        module_fail = (
            status_mismatch
            or gold_missing_tags
            or silver_missing_tags
            or transfer_missing_tags
            or gold_claim_level_missing
        )
        fail = fail or module_fail

        rows.append(
            {
                "module": module,
                "coverage_status": cov_status,
                "claims_status": cm_status,
                "papermap_status": pm_status,
                "claim_count": claim_count,
                "transfer_claims": len(transfer_claims),
                "gold_claims": len(gold_claims),
                "assumption_tags": len(paper_tags),
                "claim_level_missing": len(missing_claim_level),
                "status_check": severity(status_mismatch),
                "gold_tag_check": severity(gold_missing_tags),
                "silver_tag_check": severity(silver_missing_tags),
                "transfer_tag_check": severity(transfer_missing_tags),
                "claim_level_check": severity(gold_claim_level_missing),
                "module_result": severity(module_fail),
            }
        )

    lines = []
    lines.append("# Paper Verification Report")
    lines.append("")
    lines.append("Generated by `tools/verify_claims_consistency.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Modules checked: {len(rows)}")
    lines.append(f"- Overall result: {'FAIL' if fail else 'PASS'}")
    lines.append("")
    lines.append("## Per-paper checks")
    lines.append("")
    lines.append("| Module | Coverage | Claims | PaperMap | Claims | Gold | Transfer | Tags | Missing CL | Status Sync | Gold Tags | Silver Tags | Transfer Tags | Claim-level | Result |")
    lines.append("|---|---|---|---|---:|---:|---:|---:|---:|---|---|---|---|---|---|")
    for r in rows:
        lines.append(
            f"| {r['module']} | {r['coverage_status']} | {r['claims_status']} | {r['papermap_status']} | "
            f"{r['claim_count']} | {r['gold_claims']} | {r['transfer_claims']} | {r['assumption_tags']} | "
            f"{r['claim_level_missing']} | {r['status_check']} | {r['gold_tag_check']} | "
            f"{r['silver_tag_check']} | {r['transfer_tag_check']} | {r['claim_level_check']} | {r['module_result']} |"
        )

    lines.append("")
    lines.append("## Rules")
    lines.append("")
    lines.append("- `Status Sync`: `coverage.json`, `claims_matrix.json`, and `PaperMap.md` statuses must match.")
    lines.append("- `Gold Tags`: modules with `gold` status must expose non-empty assumption tags.")
    lines.append("- `Silver Tags`: modules with `silver` status must expose non-empty assumption tags.")
    lines.append("- `Transfer Tags`: modules with transfer mappings must expose assumption tags in matrix.")
    lines.append("- `Claim-level`: gold modules must use claim-level assumptions on gold/transfer claims.")

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {args.report}")
    return 1 if fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
